// apps/demo-site/src/Header.tsx
import IconCoffee from './assets/coffee.svg';
import IconBook from './assets/book.svg';
import IconDeviceGamepad2 from './assets/device-gamepad-2.svg';

export const Header = () => {
  return (
    <header className="w-full bg-white shadow-sm border-b border-gray-100">
      <div className="mx-auto max-w-screen-xl px-4 py-4 flex items-center justify-between">
        {/* ロゴエリア */}
        <div className="flex items-center space-x-4">
          <a
            href="/"
            className="text-2xl font-bold text-gray-800 tracking-tight hover:text-primary no-underline"
           >
            uno chan
          </a>
          <span className="text-sm text-gray-500 hidden sm:inline">with unocss animations</span>
        </div>

        {/* アクションエリア */}
        <div className="flex items-center space-x-3">
          <span className="text-sm font-semibold text-gray-700">support me !</span>
          
          {[IconCoffee, IconBook, IconDeviceGamepad2].map((icon, i) => (
            <a key={i} href="#" className="w-9 h-9 rounded-full hover:bg-gray-100 flex items-center justify-center transition-all duration-200">
              <img src={icon} alt={`icon-${i}`} className="w-5 h-5" />
            </a>
          ))}
        </div>
      </div>
    </header>
  );
};

// src/routes/Header.svelte
<script lang="ts">
  import IconCoffee from '$lib/images/coffee.svg';
  import IconBook from '$lib/images/book.svg';
  import IconDeviceGamepad2 from '$lib/images/device-gamepad-2.svg';

</script>


<div class="navbar bg-base-100">
  <div class="navbar-start">
    <a class="btn btn-ghost text-xl" href="/">
  	  uno chan demo site
    </a>
    <p>with unocess animations</p>
  </div>
  
  <div class="navbar-end">
    <p class="font-bold">寄付してください！ </p>
    <a href={''} class="btn btn-ghost btn-circle">
      <img src={IconCoffee} alt="coffee" />
    </a>
    <a href={''} class="btn btn-ghost btn-circle">
      <img src={IconBook} alt="book" />
    </a>
    <a href={''} class="btn btn-ghost btn-circle">
      <img src={IconDeviceGamepad2} alt="gamepad" />
    </a>
  </div>
</div>

<style>
</style>
