// src/routes/Header.svelte
<script lang="ts">
  import IconCoffee from '$lib/images/coffee.svg';
  import IconBook from '$lib/images/book.svg';
  import IconDeviceGamepad2 from '$lib/images/device-gamepad-2.svg';

</script>


<div class="navbar bg-base-100">
  <div class="navbar-start">
    <a class="btn btn-ghost text-xl" href="/">
  	  uno chan demo site
    </a>
    <p>with unocess animations</p>
  </div>
  
  <div class="navbar-end">
    <p class="font-bold">寄付してください！ </p>
    <a href={''} class="btn btn-ghost btn-circle">
      <img src={IconCoffee} alt="coffee" />
    </a>
    <a href={''} class="btn btn-ghost btn-circle">
      <img src={IconBook} alt="book" />
    </a>
    <a href={''} class="btn btn-ghost btn-circle">
      <img src={IconDeviceGamepad2} alt="gamepad" />
    </a>
  </div>
</div>

<style>
</style>

// apps/demo/cmponents/Header.tsx
'use client'

import React from 'react'
import Link from 'next/link'

export default function Header() {
  return (
    <header className="bg-white border-b shadow-sm">
      <div className="max-w-6xl mx-auto px-4 py-3 flex items-center justify-between">
        {/* 左側ロゴとサブタイトル */}
        <div className="flex items-center gap-4">
          <Link href="/" className="text-xl font-bold text-gray-800 hover:text-black transition">
            uno chan demo site
          </Link>
          <span className="text-sm text-gray-500">with unocss animations</span>
        </div>

        {/* 右側アクションエリア */}
        <div className="flex items-center gap-3">
          <span className="text-sm font-semibold text-gray-700">寄付してください！</span>
          <Link href="" className="p-2 rounded-full hover:bg-gray-100 transition">
            <img src="/coffee.svg" alt="coffee" className="w-6 h-6" />
          </Link>
          <Link href="" className="p-2 rounded-full hover:bg-gray-100 transition">
            <img src="/book.svg" alt="book" className="w-6 h-6" />
          </Link>
          <Link href="" className="p-2 rounded-full hover:bg-gray-100 transition">
            <img src="/device-gamepad-2.svg" alt="gamepad" className="w-6 h-6" />
          </Link>
        </div>
      </div>
    </header>
  )
}
